Updated yml

diff --git a/.github/workflows/generate-schema-versions.yml b/.github/workflows/generate-schema-versions.yml
--- a/.github/workflows/generate-schema-versions.yml
+++ b/.github/workflows/generate-schema-versions.yml
@@ -1,42 +1,37 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Generate SchemaVersions
 
-# Controls when the workflow will run
 on:
   repository_dispatch:
-    types: [shcema-updated]
-
-  # Allows you to run this workflow manually from the Actions tab
+    types: schema-updated
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout Holistic Event Repo
         uses: actions/checkout@v4
+        with:
+          path: rewards-holistic-events
 
       - name: Checkout Mock Schema Registrar
         uses: actions/checkout@v4
         with:
           repository: rr-weiyi-yu/Mock-Schema-Registrar
           token: ${{ secrets.MySecret }}
-        
-          
-      - name: Fetch schema_versions.json
-        run: |      
-          ls -R
-          cp ./schema_versions.json rewards-holistic-events/shared/src/commonMain/resources/schema_versions/schema_versions.json
+          path: Mock-Schema-Registrar
+
+      - name: Copy schema_versions.json
+        run: |
+          cp Mock-Schema-Registrar/schema_versions.json rewards-holistic-events/shared/src/commonMain/resources/schema_versions/schema_versions.json
+          if [ $? -eq 0 ]; then
+            echo "File copied successfully"
+          else
+            echo "Failed to copy file"
+            exit 1
+          fi
 
       - name: Generate SchemaVersions
+        working-directory: rewards-holistic-events
         run: ./gradlew generateSchemaVersions
-
-      - name: List files (for verification)
-        run: ls -R      
